# Generated by Django 5.1.4 on 2024-12-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_game_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image_url',
        ),
    ]
